-- Create watchlist table: stores per-user movie entries (omdb_id + watched metadata)

CREATE TABLE IF NOT EXISTS watchlist (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  omdb_id VARCHAR(100) NOT NULL,
  watched BOOLEAN NOT NULL DEFAULT FALSE,
  watched_at TIMESTAMP NULL,
  added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  scheduled_at TIMESTAMP NULL,
  CONSTRAINT fk_watchlist_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX ux_watchlist_user_movie ON watchlist(user_id, omdb_id);
CREATE INDEX idx_watchlist_user ON watchlist(user_id);


-- seed data for testing purposes


INSERT INTO watchlist (user_id, omdb_id, watched, watched_at, added_at, scheduled_at) VALUES
(1, 'tt0111161', TRUE, CURRENT_TIMESTAMP - INTERVAL '5' MONTH, CURRENT_TIMESTAMP - INTERVAL '6' MONTH, NULL),
(1, 'tt0068646', TRUE, CURRENT_TIMESTAMP - INTERVAL '4' MONTH, CURRENT_TIMESTAMP - INTERVAL '5' MONTH, NULL),
(1, 'tt0071562', TRUE, CURRENT_TIMESTAMP - INTERVAL '3' MONTH, CURRENT_TIMESTAMP - INTERVAL '4' MONTH, NULL),
(1, 'tt0120815', TRUE, CURRENT_TIMESTAMP - INTERVAL '6' DAY, CURRENT_TIMESTAMP - INTERVAL '20' DAY, NULL), -- last week
(1, 'tt0172495', TRUE, CURRENT_TIMESTAMP - INTERVAL '28' DAY, CURRENT_TIMESTAMP - INTERVAL '2' MONTH, NULL), -- last month
(1, 'tt0109830', TRUE, CURRENT_TIMESTAMP - INTERVAL '380' DAY, CURRENT_TIMESTAMP - INTERVAL '390' DAY, NULL), -- last year
(2, 'tt0468569', TRUE, CURRENT_TIMESTAMP - INTERVAL '2' MONTH, CURRENT_TIMESTAMP - INTERVAL '3' MONTH, NULL),
(2, 'tt0050083', TRUE, CURRENT_TIMESTAMP - INTERVAL '1' MONTH, CURRENT_TIMESTAMP - INTERVAL '2' MONTH, NULL),
(2, 'tt0108052', TRUE, CURRENT_TIMESTAMP - INTERVAL '15' DAY, CURRENT_TIMESTAMP - INTERVAL '1' MONTH, NULL),
(2, 'tt0816692', TRUE, CURRENT_TIMESTAMP - INTERVAL '9' DAY, CURRENT_TIMESTAMP - INTERVAL '12' DAY, NULL), -- last week-ish
(2, 'tt0133093', TRUE, CURRENT_TIMESTAMP - INTERVAL '30' DAY, CURRENT_TIMESTAMP - INTERVAL '40' DAY, NULL), -- last month
(2, 'tt0169547', TRUE, CURRENT_TIMESTAMP - INTERVAL '320' DAY, CURRENT_TIMESTAMP - INTERVAL '330' DAY, NULL), -- last year window
(3, 'tt0167260', TRUE, CURRENT_TIMESTAMP - INTERVAL '10' DAY, CURRENT_TIMESTAMP - INTERVAL '20' DAY, NULL),
(3, 'tt0110912', TRUE, CURRENT_TIMESTAMP - INTERVAL '5' DAY, CURRENT_TIMESTAMP - INTERVAL '15' DAY, NULL),
(3, 'tt0137523', TRUE, CURRENT_TIMESTAMP - INTERVAL '2' DAY, CURRENT_TIMESTAMP - INTERVAL '10' DAY, NULL),
(3, 'tt0088763', TRUE, CURRENT_TIMESTAMP - INTERVAL '7' DAY, CURRENT_TIMESTAMP - INTERVAL '12' DAY, NULL), -- last week
(3, 'tt0103064', TRUE, CURRENT_TIMESTAMP - INTERVAL '35' DAY, CURRENT_TIMESTAMP - INTERVAL '50' DAY, NULL), -- last month
(3, 'tt0268978', TRUE, CURRENT_TIMESTAMP - INTERVAL '410' DAY, CURRENT_TIMESTAMP - INTERVAL '420' DAY, NULL); -- last year
